// File: BrentKung.v
// Generated by MyHDL 0.11
// Date: Thu Sep 16 22:54:57 2021


`timescale 1ns/10ps

module BrentKung (
    OUTS,
    INPUTS
);


output [12:0] OUTS;
wire [12:0] OUTS;
input [23:0] INPUTS;

wire [12:0] outs_vec;
wire [0:0] PG_Generator10_g;
wire [0:0] PG_Generator10_p;
wire [0:0] PG_Generator11_g;
wire [0:0] PG_Generator11_p;
wire [0:0] PG_Generator12_g;
wire [0:0] PG_Generator12_p;
wire [0:0] PG_Generator13_g;
wire [0:0] PG_Generator13_p;
wire [0:0] PG_Generator14_g;
wire [0:0] PG_Generator14_p;
wire [0:0] PG_Generator15_g;
wire [0:0] PG_Generator15_p;
wire [0:0] PG_Generator16_g;
wire [0:0] PG_Generator16_p;
wire [0:0] PG_Generator17_g;
wire [0:0] PG_Generator17_p;
wire [0:0] PG_Generator18_g;
wire [0:0] PG_Generator18_p;
wire [0:0] PG_Generator19_g;
wire [0:0] PG_Generator19_p;
wire [0:0] PG_Generator110_g;
wire [0:0] PG_Generator110_p;
wire [0:0] PG_Generator111_g;
wire [0:0] PG_Generator111_p;
wire [0:0] GrayCircle0_go;
wire [0:0] BlackCircle0_go;
wire [0:0] BlackCircle0_po;
wire [0:0] BlackCircle1_go;
wire [0:0] BlackCircle1_po;
wire [0:0] BlackCircle2_go;
wire [0:0] BlackCircle2_po;
wire [0:0] GrayCircle1_go;
wire [0:0] BlackCircle3_go;
wire [0:0] BlackCircle3_po;
wire [0:0] GrayCircle2_go;
wire [0:0] BlackCircle4_go;
wire [0:0] BlackCircle4_po;
wire [0:0] BlackCircle5_go;
wire [0:0] BlackCircle5_po;
wire [0:0] BlackCircle6_go;
wire [0:0] BlackCircle6_po;
wire [0:0] GrayCircle3_go;
wire [0:0] GrayCircle4_go;
wire [0:0] GrayCircle5_go;
wire [0:0] GrayCircle6_go;
wire [0:0] GrayCircle7_go;
wire [0:0] GrayCircle8_go;
wire [0:0] GrayCircle9_go;
wire [0:0] GrayCircle10_go;
wire [0:0] FinalSum0_sum;
wire [0:0] FinalSum1_sum;
wire [0:0] FinalSum2_sum;
wire [0:0] FinalSum3_sum;
wire [0:0] FinalSum4_sum;
wire [0:0] FinalSum5_sum;
wire [0:0] FinalSum6_sum;
wire [0:0] FinalSum7_sum;
wire [0:0] FinalSum8_sum;
wire [0:0] FinalSum9_sum;
wire [0:0] FinalSum10_sum;

assign outs_vec[12] = GrayCircle10_go[0];
assign outs_vec[11] = FinalSum10_sum[0];
assign outs_vec[10] = FinalSum9_sum[0];
assign outs_vec[9] = FinalSum8_sum[0];
assign outs_vec[8] = FinalSum7_sum[0];
assign outs_vec[7] = FinalSum6_sum[0];
assign outs_vec[6] = FinalSum5_sum[0];
assign outs_vec[5] = FinalSum4_sum[0];
assign outs_vec[4] = FinalSum3_sum[0];
assign outs_vec[3] = FinalSum2_sum[0];
assign outs_vec[2] = FinalSum1_sum[0];
assign outs_vec[1] = FinalSum0_sum[0];
assign outs_vec[0] = PG_Generator10_p[0];



assign PG_Generator10_p = (INPUTS[0] ^ INPUTS[1]);
assign PG_Generator10_g = (INPUTS[0] & INPUTS[1]);



assign PG_Generator11_p = (INPUTS[2] ^ INPUTS[3]);
assign PG_Generator11_g = (INPUTS[2] & INPUTS[3]);



assign PG_Generator12_p = (INPUTS[4] ^ INPUTS[5]);
assign PG_Generator12_g = (INPUTS[4] & INPUTS[5]);



assign PG_Generator13_p = (INPUTS[6] ^ INPUTS[7]);
assign PG_Generator13_g = (INPUTS[6] & INPUTS[7]);



assign PG_Generator14_p = (INPUTS[8] ^ INPUTS[9]);
assign PG_Generator14_g = (INPUTS[8] & INPUTS[9]);



assign PG_Generator15_p = (INPUTS[10] ^ INPUTS[11]);
assign PG_Generator15_g = (INPUTS[10] & INPUTS[11]);



assign PG_Generator16_p = (INPUTS[12] ^ INPUTS[13]);
assign PG_Generator16_g = (INPUTS[12] & INPUTS[13]);



assign PG_Generator17_p = (INPUTS[14] ^ INPUTS[15]);
assign PG_Generator17_g = (INPUTS[14] & INPUTS[15]);



assign PG_Generator18_p = (INPUTS[16] ^ INPUTS[17]);
assign PG_Generator18_g = (INPUTS[16] & INPUTS[17]);



assign PG_Generator19_p = (INPUTS[18] ^ INPUTS[19]);
assign PG_Generator19_g = (INPUTS[18] & INPUTS[19]);



assign PG_Generator110_p = (INPUTS[20] ^ INPUTS[21]);
assign PG_Generator110_g = (INPUTS[20] & INPUTS[21]);



assign PG_Generator111_p = (INPUTS[22] ^ INPUTS[23]);
assign PG_Generator111_g = (INPUTS[22] & INPUTS[23]);



assign GrayCircle0_go = (PG_Generator11_g | (PG_Generator11_p & PG_Generator10_g));



assign BlackCircle0_po = (PG_Generator13_p & PG_Generator12_p);
assign BlackCircle0_go = (PG_Generator13_g | (PG_Generator13_p & PG_Generator12_g));



assign BlackCircle1_po = (PG_Generator15_p & PG_Generator14_p);
assign BlackCircle1_go = (PG_Generator15_g | (PG_Generator15_p & PG_Generator14_g));



assign BlackCircle2_po = (PG_Generator17_p & PG_Generator16_p);
assign BlackCircle2_go = (PG_Generator17_g | (PG_Generator17_p & PG_Generator16_g));



assign GrayCircle1_go = (BlackCircle0_go | (BlackCircle0_po & GrayCircle0_go));



assign BlackCircle3_po = (BlackCircle2_po & BlackCircle1_po);
assign BlackCircle3_go = (BlackCircle2_go | (BlackCircle2_po & BlackCircle1_go));



assign GrayCircle2_go = (BlackCircle3_go | (BlackCircle3_po & GrayCircle1_go));



assign BlackCircle4_po = (PG_Generator19_p & PG_Generator18_p);
assign BlackCircle4_go = (PG_Generator19_g | (PG_Generator19_p & PG_Generator18_g));



assign BlackCircle5_po = (PG_Generator111_p & PG_Generator110_p);
assign BlackCircle5_go = (PG_Generator111_g | (PG_Generator111_p & PG_Generator110_g));



assign BlackCircle6_po = (BlackCircle5_po & BlackCircle4_po);
assign BlackCircle6_go = (BlackCircle5_go | (BlackCircle5_po & BlackCircle4_go));



assign GrayCircle3_go = (PG_Generator12_g | (PG_Generator12_p & GrayCircle0_go));



assign GrayCircle4_go = (PG_Generator14_g | (PG_Generator14_p & GrayCircle1_go));



assign GrayCircle5_go = (BlackCircle1_go | (BlackCircle1_po & GrayCircle1_go));



assign GrayCircle6_go = (PG_Generator16_g | (PG_Generator16_p & GrayCircle5_go));



assign GrayCircle7_go = (PG_Generator18_g | (PG_Generator18_p & GrayCircle2_go));



assign GrayCircle8_go = (BlackCircle4_go | (BlackCircle4_po & GrayCircle2_go));



assign GrayCircle9_go = (PG_Generator110_g | (PG_Generator110_p & GrayCircle8_go));



assign GrayCircle10_go = (BlackCircle6_go | (BlackCircle6_po & GrayCircle2_go));



assign FinalSum0_sum = (PG_Generator11_p ^ PG_Generator10_g);



assign FinalSum1_sum = (PG_Generator12_p ^ GrayCircle0_go);



assign FinalSum2_sum = (PG_Generator13_p ^ GrayCircle3_go);



assign FinalSum3_sum = (PG_Generator14_p ^ GrayCircle1_go);



assign FinalSum4_sum = (PG_Generator15_p ^ GrayCircle4_go);



assign FinalSum5_sum = (PG_Generator16_p ^ GrayCircle5_go);



assign FinalSum6_sum = (PG_Generator17_p ^ GrayCircle6_go);



assign FinalSum7_sum = (PG_Generator18_p ^ GrayCircle2_go);



assign FinalSum8_sum = (PG_Generator19_p ^ GrayCircle7_go);



assign FinalSum9_sum = (PG_Generator110_p ^ GrayCircle8_go);



assign FinalSum10_sum = (PG_Generator111_p ^ GrayCircle9_go);



assign OUTS = outs_vec;

endmodule
